"""Measured-data path: RINSE descriptors from an experimental reflection list.

This module builds a :class:`~rinse_descriptor._structure_factors.ReflectionList`
from a *measured* set of reflections (an ``.hkl`` file of ``h k l I σ`` records)
plus a unit cell and space group (from a ``.cif``/``.res``/``.ins`` file or a
supplied cell), i.e. *without* an atomic model.

Completeness requirement
-------------------------
The measured data must cover a full reflection sphere out to
``params.q_cutoff = qmax_factor · q_max`` (1.2·q_max by default) so that the
Gaussian tails of the outermost radial shells are supported.  The user may
supply either a full sphere or a hemisphere; Friedel mates ``(-h,-k,-l)`` are
generated by inversion symmetry (Friedel's law, ``I(-G) = I(G)``).

Systematically absent reflections are excluded from the expected set, so they are
never counted as missing.  Any *expected* reflection the user did not supply is
zero-filled — it contributes nothing to the intensity-weighted descriptor — but
if more than ``max_missing_fraction`` (1 %) of expected reflections are missing
a :class:`MeasuredCompletenessError` is raised.
"""

from __future__ import annotations

import os
from collections.abc import Sequence
from typing import IO, Any, cast

import numpy as np
from numpy.typing import NDArray

from ._cctbx_import_patch import patch_cctbx_imports
from ._descriptor import RinseParams
from ._structure_factors import ReflectionList


class MeasuredCompletenessError(ValueError):
    """Raised when the supplied reflections do not cover the required sphere."""


# ---------------------------------------------------------------------------
# HKL reading
# ---------------------------------------------------------------------------


def load_hkl(
    path: str | os.PathLike[str] | IO[bytes] | IO[str],
) -> tuple[NDArray[np.int32], NDArray[np.float64], NDArray[np.float64]]:
    """Read a SHELX-style ``.hkl`` reflection file.

    Each data record is ``h k l I σ`` where ``I`` is the measured intensity
    (``|F|²``) and ``σ`` its standard uncertainty.  Both fixed-width SHELX
    ``HKLF 4`` format (``3I4,2F8.2``) and whitespace-separated free format are
    accepted.  Reading stops at the SHELX terminator record ``0 0 0`` (or end
    of file); the ``(0,0,0)`` reflection itself is dropped.

    Returns
    -------
    hkl : (M, 3) int32
    intensity : (M,) float64
    sigma : (M,) float64  – zero where the file provides no σ column.
    """
    text = _read_text(path)

    hs: list[tuple[int, int, int]] = []
    intensities: list[float] = []
    sigmas: list[float] = []

    for line in text.splitlines():
        if not line.strip():
            continue
        parsed = _parse_hkl_line(line)
        if parsed is None:
            continue
        h, k, ell, intensity, sigma = parsed
        if h == 0 and k == 0 and ell == 0:
            break  # SHELX HKLF terminator
        hs.append((h, k, ell))
        intensities.append(intensity)
        sigmas.append(sigma)

    if not hs:
        raise ValueError(f"HKL file {path!r} contains no reflections")

    return (
        np.asarray(hs, dtype=np.int32),
        np.asarray(intensities, dtype=np.float64),
        np.asarray(sigmas, dtype=np.float64),
    )


def _parse_hkl_line(line: str) -> tuple[int, int, int, float, float] | None:
    """Parse a single HKL record, trying free format then fixed-width HKLF 4."""
    tokens = line.split()
    if len(tokens) >= 4:
        try:
            h, k, ell = int(tokens[0]), int(tokens[1]), int(tokens[2])
            intensity = float(tokens[3])
            sigma = float(tokens[4]) if len(tokens) >= 5 else 0.0
            return h, k, ell, intensity, sigma
        except ValueError:
            pass  # fall through to fixed-width

    # Fixed-width SHELX HKLF 4: 3I4, 2F8.2 (indices may run together).
    if len(line) >= 12:
        try:
            h = int(line[0:4])
            k = int(line[4:8])
            ell = int(line[8:12])
            intensity = float(line[12:20]) if len(line) >= 20 and line[12:20].strip() else 0.0
            sigma = float(line[20:28]) if len(line) >= 28 and line[20:28].strip() else 0.0
            return h, k, ell, intensity, sigma
        except ValueError:
            return None
    return None


def _read_text(path: str | os.PathLike[str] | IO[bytes] | IO[str]) -> str:
    if hasattr(path, "read"):
        reader = cast("IO[bytes]", path)
        raw = reader.read()
        return raw.decode("utf-8", errors="replace") if isinstance(raw, bytes) else raw
    with open(str(path), encoding="utf-8", errors="replace") as f:
        return f.read()


# ---------------------------------------------------------------------------
# Crystal symmetry (unit cell + space group) without an atomic model
# ---------------------------------------------------------------------------


def load_crystal_symmetry(
    source: str | os.PathLike[str] | Sequence[float],
    *,
    space_group: str | None = None,
) -> Any:
    """Return a :class:`cctbx.crystal.symmetry` for the measured cell.

    Parameters
    ----------
    source:
        Either a path to a ``.cif``/``.res``/``.ins`` file (unit cell and space
        group are extracted without requiring atomic sites), or a sequence of
        six unit-cell parameters ``(a, b, c, α, β, γ)``.
    space_group:
        Hermann–Mauguin symbol overriding the space group from *source*
        (required when *source* is a bare cell and the lattice is centred;
        defaults to ``P 1``).
    """
    patch_cctbx_imports()

    from cctbx import crystal, uctbx

    if isinstance(source, (str, os.PathLike)):
        import iotbx.crystal_symmetry_from_any as csfa

        cs = csfa.extract_from(str(source))
        if cs is None or cs.unit_cell() is None:
            raise ValueError(f"Could not extract a unit cell from {source!r}")
        if space_group is not None:
            cs = crystal.symmetry(unit_cell=cs.unit_cell(), space_group_symbol=space_group)
        elif cs.space_group_info() is None:
            cs = crystal.symmetry(unit_cell=cs.unit_cell(), space_group_symbol="P 1")
        return cs

    params = [float(x) for x in source]
    if len(params) != 6:
        raise ValueError(f"Cell must be six parameters (a, b, c, α, β, γ), got {len(params)}")
    return crystal.symmetry(
        unit_cell=uctbx.unit_cell(tuple(params)),
        space_group_symbol=space_group or "P 1",
    )


# ---------------------------------------------------------------------------
# Reflection-list construction with completeness checking
# ---------------------------------------------------------------------------


def reflections_from_measured(
    hkl: NDArray[np.integer],
    intensity: NDArray[np.floating],
    symmetry: Any,
    *,
    params: RinseParams | None = None,
    max_missing_fraction: float = 0.001,
    debug: bool = False,
) -> ReflectionList:
    """Build a :class:`ReflectionList` from measured reflections.

    Symmetry-equivalent and redundant measurements are merged (mean intensity),
    completeness is checked against the non-absent reflections expected out to
    ``params.q_cutoff``, missing reflections are zero-filled, and the result is
    expanded to the full sphere (Friedel mates by inversion).

    Raises
    ------
    MeasuredCompletenessError
        If more than ``max_missing_fraction`` of expected reflections are
        missing.
    """
    patch_cctbx_imports()

    from cctbx import miller
    from cctbx.array_family import flex

    if params is None:
        params = RinseParams()

    d_min = 1.0 / params.q_cutoff

    hkl = np.asarray(hkl, dtype=np.int64).reshape(-1, 3)
    intensity = np.asarray(intensity, dtype=np.float64).reshape(-1)
    if hkl.shape[0] != intensity.shape[0]:
        raise ValueError("hkl and intensity must have the same length")

    # Drop (0,0,0); it carries no orientation information.
    keep = ~np.all(hkl == 0, axis=1)
    hkl = hkl[keep]
    intensity = intensity[keep]

    mi = flex.miller_index([(int(a), int(b), int(c)) for a, b, c in hkl])
    ms = miller.set(crystal_symmetry=symmetry, indices=mi, anomalous_flag=False)
    ma = ms.array(data=flex.double(intensity.tolist()))

    # Merge symmetry-equivalent and redundant observations onto the asymmetric
    # unit (Friedel's law: anomalous_flag=False folds (h) and (-h) together).
    merged = ma.merge_equivalents(use_internal_variance=False).array()
    merged = merged.resolution_filter(d_min=d_min)

    # Expected reflections = non-absent complete set to the cutoff resolution.
    complete = merged.complete_set(d_min=d_min)
    n_expected = complete.size()
    n_missing = complete.lone_set(merged).size() if n_expected else 0
    missing_fraction = (n_missing / n_expected) if n_expected else 0.0

    if debug:
        print(
            f"[rinse_descriptor] measured: d_min={d_min:.4f} Å  "
            f"expected={n_expected}  supplied={merged.size()}  "
            f"missing={n_missing} ({missing_fraction:.2%})"
        )

    if missing_fraction > max_missing_fraction:
        raise MeasuredCompletenessError(
            f"Incomplete reflection sphere: {n_missing} of {n_expected} expected "
            f"reflections missing ({missing_fraction:.2%}) out to "
            f"|G| ≤ {params.q_cutoff:.3f} Å⁻¹ (d = {d_min:.3f} Å), which exceeds "
            f"the {max_missing_fraction:.2%} tolerance. Supply a full sphere (or "
            f"hemisphere) of reflections to at least {params.qmax_factor:g}×q_max."
        )

    # Zero-fill missing expected reflections, then expand to the full sphere.
    filled = merged.complete_array(new_data_value=0.0, d_min=d_min)
    p1 = filled.expand_to_p1()  # symmetry equivalents (hemisphere in P1)

    hkl_hemi = np.asarray([(int(a), int(b), int(c)) for a, b, c in p1.indices()], dtype=np.int64)
    intensity_hemi = np.asarray(p1.data(), dtype=np.float64)

    # Friedel mates by inversion symmetry -> full sphere; de-duplicate.
    hkl_full = np.vstack([hkl_hemi, -hkl_hemi])
    intensity_full = np.concatenate([intensity_hemi, intensity_hemi])
    _, unique_idx = np.unique(hkl_full, axis=0, return_index=True)
    order = np.sort(unique_idx)
    hkl_full = hkl_full[order]
    intensity_full = intensity_full[order]

    # Cartesian reciprocal vectors G = h·a* + k·b* + l·c* (no 2π), |G| = 2 sinθ/λ.
    uc = symmetry.unit_cell()
    orth = np.asarray(uc.orthogonalization_matrix(), dtype=np.float64).reshape(3, 3)
    recip = np.linalg.inv(orth.T).T

    q_vectors = hkl_full.astype(np.float64) @ recip
    q_magnitudes = np.linalg.norm(q_vectors, axis=1)

    mask = q_magnitudes > 1e-9
    return ReflectionList(
        hkl=hkl_full[mask].astype(np.int32),
        q_vectors=q_vectors[mask],
        q_magnitudes=q_magnitudes[mask],
        intensities=intensity_full[mask],
    )
